### ISSUE TITLE
Add support for WikiTree

### ISSUE THREAD

**Issue by justincy** [rootsdev/genscrape#13]

**Comment by justincy** [comment]
The best way to support WikiTree is via https://github.com/rootsdev/genscrape/issues/14

**Comment by MatForsberg** [comment]
Making some progress. Have Person, Birth info, Death info, and parents names. 

WikiTree shows multiple marriages, example( http://www.wikitree.com/wiki/Roosevelt-18 ). Which spouse should be used for personData?

**Comment by justincy** [comment]
I would go with the first spouse so that it's deterministic. I have toyed with the idea to support a more flexible and complete schema, but it's a lot of work.

**Comment by justincy** [comment]
Closed by #16
