### ISSUE TITLE
Schema upgrade to GEDCOM X

### ISSUE THREAD

**Issue by justincy** [rootsdev/genscrape#19]
genscrape uses the [gensearch schema](https://github.com/rootsdev/gensearch#schema). It's a simple schema designed for searching on genealogy websites. But genscrape has many more use cases and ought have a more advanced schema with first-class support for multiple persons, relationships, and sources.

```
{
    "persons": [],
    "relationships": [],
    "sources": []
}
```

That looks very similar to the [GEDCOM X JSON format](https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#12-examples), with the only exception being that GEDCOM X has `sourceDescriptions` instead of `sources`. Despite how much I dislike the term `sourceDescriptions` and it's schema, I ___really___ like the idea of not having to create my own data format.

**Comment by dovy** [comment]
Not opposed to that, but we should expand the model. I'm fine with using a "standard" but i'm not fine having endless nested objects to get something that should be easy.

Plus we should have a bigger model for genscrape anyways.  ;)

**Comment by justincy** [comment]
> Plus we should have a bigger model for genscrape anyways. ;)

Could you expound?

**Comment by dovy** [comment]
Just making sure we can have more types of elements. Example is relationships, children, marriage, etc. Stuff that we could expand in a repeatable object to expand different types of records.

**Comment by justincy** [comment]
If we used GEDCOM X we would need a library which makes it easier to work with the data types. 

FamilySearch has [client libraries](https://familysearch.org/developers/libraries) available in various languages, but not JavaScript. They use [enunciate](https://github.com/stoicflame/enunciate) to automatically generate those libraries but enunciate [doesn't support JavaScript](https://github.com/stoicflame/enunciate/issues/378).

We could create the library by hand. There are currently 46 data types and 14 enums. That would be pretty tedious to setup by hand. Any takers? Adding types would be easier but it would also be a pain to refactor if we decided to change our approach (prototypes vs es6 classes vs factories).

**Comment by justincy** [comment]
Using enunciate would require a significant amount of time to add support for JavaScript. Plus we would still need to write helper methods such as [`Person.getFacts(type)`](https://github.com/FamilySearch/gedcomx-java/blob/a4959a093979f30c93c90ab8e131b2684034cf5c/gedcomx-model/src/main/java/org/gedcomx/conclusion/Person.java#L477-L494) that is in the Java code. I say those methods are necessary based on my experience using GEDCOM X data in the FamilySearch JS SDK.

While we're on that note, we can't use the classes from the JS SDK because 1) they don't always follow the spec and 2) they were designed for an HTTP client and therefore have async methods designed for interacting with the API.

**Comment by justincy** [comment]
I'm tracking design of the GEDCOM X JS library here: https://github.com/rootsdev/gedcomx-js/issues

I've submitted a [PR to enunciate for supporting JavaScript](https://github.com/stoicflame/enunciate/pull/382) but I'm still probably not going to use it.

**Comment by justincy** [comment]
I finished the first version of https://github.com/rootsdev/gedcomx-js. I'm committed to using that as the data model for the next version of genscrape. I will begin work on that this week; maybe even today.
