### ISSUE TITLE
Chrome/Firefox extension?

### ISSUE THREAD

**Issue by alexreg** [rootsdev/genscrape#84]
Is there actually a Chrome/Firefox extension that makes use of this library?

I'm particularly interested in the functionality for scraping a tree from a website like Ancestry.com.

**Comment by dovy** [comment]
RecordSeek for Chrome uses it. ;)

**Comment by alexreg** [comment]
Thanks, I'll give it a go!

**Comment by dallyhorton** [comment]
WikiTree X also uses this.
